version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1337:1337
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: basedbase
      JWT_SECRET: superduper53cr37youwillnevergu35517

  mysql:
    build:
      context: ./CVExchange/db
      dockerfile: Dockerfile
    volumes:
      - cvexchange-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: basedbase

volumes:
  cvexchange-mysql-data:
