version: '3'

services:
  cvexchange-checker:
    build: .
    # The checker runs a HTTP interfaces, so we need to map port 3031 to the outside (port 8000).
    ports:
      - 7331:8000
    environment:
      - MONGO_ENABLED=1
      - MONGO_HOST=cvexchange-mongo
      - MONGO_PORT=27017
      - MONGO_USER=cvexchange
      - MONGO_PASSWORD=cvexchange

  # The python checkerlib requires a mongo db!
  cvexchange-mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: cvexchange
      MONGO_INITDB_ROOT_PASSWORD: cvexchange